name = "WeenieCraft 1.21.5"
author = "Karteufel"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "6459ff2caad962a5200a9f47a7ded6c021e6628fa587c969a125eca6674cc589"

[versions]
fabric = "0.16.13"
minecraft = "1.21.5"
