name = "WeenieCraft 1.21.5"
author = "Karteufel"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "d62cfb1c668f2e5c37c9d41c6b73e23cd6e880d376c2866a1cab56a79fde25f1"

[versions]
fabric = "0.16.13"
minecraft = "1.21.5"
