name = "WeenieCraft 1.21.5"
author = "Karteufel"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "93f4823d0e232b6a90b154708eb0841c5f454636d9fab48b8a0455ef9db3a56e"

[versions]
fabric = "0.16.13"
minecraft = "1.21.5"
